services:
    app:
        build: .
        container_name: gb-best-of-automation
        working_dir: /app
        volumes:
            - .:/app
        environment:
            - NODE_ENV=${NODE_ENV}